spring:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
#    hibernate:
#      ddl-auto: validate
  datasource:
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 30000
    validationQuery: SELECT 1
    url: jdbc:h2:mem:testdb/rps
    driverClassName: org.h2.Driver
    username: root
    password: root
    data: classpath:/db/data.sql
    initialization-mode: always
  h2:
    console:
      enabled: true
      path: /h2-console
server:
  port: 8081

management.health.db.enabled: true
management.endpoint.health.show-details: always
